import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CosmicBackground } from '@/components/cosmic/CosmicBackground';
import { Brain, TrendingUp, Lightbulb, Share2, Download, ArrowLeft } from 'lucide-react';
import { db } from '@/db/api';
import type { UserAssessment, Assessment } from '@/types/types';
import { toast } from 'sonner';
import { formatDistanceToNow } from 'date-fns';

export default function AssessmentResults() {
  const { id } = useParams<{ id: string }>();
  const { profile } = useAuth();
  const navigate = useNavigate();
  const [assessment, setAssessment] = useState<Assessment | null>(null);
  const [userAssessment, setUserAssessment] = useState<UserAssessment | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id && profile) {
      loadResults();
    }
  }, [id, profile]);

  const loadResults = async () => {
    if (!id || !profile) return;

    try {
      const assessmentData = await db.assessments.getById(id);
      if (!assessmentData) {
        toast.error('Assessment not found');
        navigate('/assessments');
        return;
      }
      setAssessment(assessmentData);

      const userAssessments = await db.userAssessments.list(profile.id);
      const latestResult = userAssessments
        .filter(ua => ua.assessment_id === id)
        .sort((a, b) => new Date(b.completed_at).getTime() - new Date(a.completed_at).getTime())[0];

      if (!latestResult) {
        toast.error('No results found for this assessment');
        navigate(`/assessment/${id}`);
        return;
      }

      setUserAssessment(latestResult);
    } catch (error) {
      console.error('Error loading results:', error);
      toast.error('Failed to load results');
      navigate('/assessments');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = () => {
    if (!assessment) return;
    
    const shareText = `I just completed the "${assessment.title}" assessment on Newomen! 🌟`;
    if (navigator.share) {
      navigator.share({
        title: assessment.title,
        text: shareText,
        url: window.location.href,
      }).catch(() => {
        navigator.clipboard.writeText(`${shareText} ${window.location.href}`);
        toast.success('Link copied to clipboard');
      });
    } else {
      navigator.clipboard.writeText(`${shareText} ${window.location.href}`);
      toast.success('Link copied to clipboard');
    }
  };

  const handleDownload = () => {
    if (!assessment || !userAssessment) return;

    const insights = (userAssessment.ai_insights || {}) as Record<string, unknown>;
    const content = `
${assessment.title}
Completed: ${formatDistanceToNow(new Date(userAssessment.completed_at), { addSuffix: true })}

${insights.summary || ''}

Key Traits:
${(insights.traits as string[] || []).map((t: string) => `• ${t}`).join('\n')}

Recommendations:
${(insights.recommendations as string[] || []).map((r: string) => `• ${r}`).join('\n')}

---
Generated by Newomen - Your AI Self-Discovery Platform
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${assessment.title.replace(/\s+/g, '-')}-results.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Results downloaded');
  };

  if (loading) {
    return (
      <div className="min-h-screen relative flex items-center justify-center">
        <CosmicBackground />
        <div className="relative z-10">
          <p className="text-muted-foreground">Loading results...</p>
        </div>
      </div>
    );
  }

  if (!assessment || !userAssessment) {
    return (
      <div className="min-h-screen relative flex items-center justify-center">
        <CosmicBackground />
        <div className="relative z-10">
          <Card className="glass-card">
            <CardContent className="py-12 text-center">
              <p className="text-muted-foreground">Results not available</p>
              <Button onClick={() => navigate('/assessments')} className="mt-4">
                Back to Assessments
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  const insights = (userAssessment.ai_insights || {}) as Record<string, unknown>;
  const traits = (insights.traits as string[]) || [];
  const recommendations = (insights.recommendations as string[]) || [];
  const avgScore = insights.average_score as number | undefined;

  return (
    <div className="min-h-screen relative">
      <CosmicBackground />
      
      <div className="relative z-10 container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-8">
          <Link to="/assessments">
            <Button variant="ghost" className="mb-4">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Assessments
            </Button>
          </Link>
          <h1 className="text-4xl font-bold mb-2">
            <span className="gradient-text">{assessment.title}</span>
          </h1>
          <p className="text-muted-foreground">
            Completed {formatDistanceToNow(new Date(userAssessment.completed_at), { addSuffix: true })}
          </p>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
          <Card className="glass-card">
            <CardContent className="pt-6">
              <div className="text-center">
                <Brain className="w-12 h-12 mx-auto mb-3 text-primary" />
                <div className="text-3xl font-bold gradient-text">
                  {(insights.total_questions as number) || 0}
                </div>
                <p className="text-sm text-muted-foreground">Questions Answered</p>
              </div>
            </CardContent>
          </Card>

          {avgScore !== undefined && (
            <Card className="glass-card">
              <CardContent className="pt-6">
                <div className="text-center">
                  <TrendingUp className="w-12 h-12 mx-auto mb-3 text-secondary" />
                  <div className="text-3xl font-bold gradient-text">
                    {avgScore.toFixed(1)}/10
                  </div>
                  <p className="text-sm text-muted-foreground">Average Score</p>
                </div>
              </CardContent>
            </Card>
          )}

          <Card className="glass-card">
            <CardContent className="pt-6">
              <div className="text-center">
                <Lightbulb className="w-12 h-12 mx-auto mb-3 text-accent" />
                <div className="text-3xl font-bold gradient-text">
                  {traits.length}
                </div>
                <p className="text-sm text-muted-foreground">Key Traits Identified</p>
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="glass-card border-primary/30 cosmic-glow mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="w-5 h-5" />
              Your Insights
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <h3 className="font-semibold mb-3">Summary</h3>
              <p className="text-muted-foreground leading-relaxed">
                {(insights.summary as string) || 'Your assessment reveals unique patterns and characteristics.'}
              </p>
            </div>

            {traits.length > 0 && (
              <div>
                <h3 className="font-semibold mb-3">Key Traits</h3>
                <div className="flex flex-wrap gap-2">
                  {traits.map((trait, index) => (
                    <Badge key={index} variant="secondary" className="text-sm py-1 px-3">
                      {trait}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {recommendations.length > 0 && (
              <div>
                <h3 className="font-semibold mb-3">Recommendations</h3>
                <ul className="space-y-2">
                  {recommendations.map((rec, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <div className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                        <span className="text-xs font-semibold text-primary">{index + 1}</span>
                      </div>
                      <p className="text-muted-foreground flex-1">{rec}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="glass-card mb-6">
          <CardHeader>
            <CardTitle>What's Next?</CardTitle>
            <CardDescription>
              Continue your self-discovery journey
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
              <Link to="/chat">
                <Button variant="outline" className="w-full justify-start">
                  <Brain className="w-4 h-4 mr-2" />
                  Discuss with NewMe
                </Button>
              </Link>
              <Link to="/assessments">
                <Button variant="outline" className="w-full justify-start">
                  <TrendingUp className="w-4 h-4 mr-2" />
                  Take Another Assessment
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>

        <div className="flex gap-4">
          <Button onClick={handleShare} variant="outline" className="flex-1">
            <Share2 className="w-4 h-4 mr-2" />
            Share Results
          </Button>
          <Button onClick={handleDownload} variant="outline" className="flex-1">
            <Download className="w-4 h-4 mr-2" />
            Download
          </Button>
          <Link to={`/assessment/${assessment.id}`} className="flex-1">
            <Button className="w-full cosmic-gradient">
              Retake Assessment
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
